# Firewall Application Configuration
# This file demonstrates all available configuration options

server:
  port: 8081
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  mode: "debug"  # debug, release, production

database:
  host: "127.0.0.1"
  port: 3306
  user: "user"
  password: "password"
  name: "firewall"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  conn_max_idle_time: "1m"
  ssl_mode: "false"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"

elastic:
  hosts:
    - "http://localhost:9200"
  username: ""
  password: ""
  timeout: "30s"
  index: "firewall"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  timeout: "5s"

logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file path
  max_size: 100  # MB
  max_backups: 3
  max_age: 28  # days
  compress: true

security:
  cors_enabled: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8081"
  cors_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  cors_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  rate_limit: 1000
  rate_limit_window: "1m"

# Distributed locking configuration
locking:
  distributed: false  # Set to true for horizontal scaling (requires Redis)
  lock_ttl: "5m"
  incremental_ttl: "5m"
  full_sync_ttl: "30m"
  cleanup_interval: "10m"

# Caching configuration
caching:
  distributed: false  # Set to true for horizontal scaling (requires Redis)
  default_ttl: "5m"
  filter_ttl: "5m"
  list_ttl: "2m"
  stats_ttl: "30s" 